name: ci-cd

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: 'false'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Check code style with black
        run: black --check .

      - name: Check imports ordering with isort
        run: isort -c .

      - name: Lint with flake8
        run: flake8 .

  publish:
    needs: tests
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Building package
        run: pip install poetry && poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
